# Generated by Django 4.0.1 on 2023-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='country',
            field=models.CharField(default='Россия', max_length=80),
        ),
        migrations.AddField(
            model_name='short',
            name='model',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='short',
            name='season',
            field=models.CharField(default='Мульти', max_length=60),
        ),
        migrations.AddField(
            model_name='short',
            name='sex',
            field=models.CharField(default='Мужской', max_length=40),
        ),
        migrations.AddField(
            model_name='short',
            name='size',
            field=models.CharField(default='До линии бедер', max_length=100),
        ),
        migrations.AddField(
            model_name='short',
            name='style',
            field=models.CharField(default='Повседневный', max_length=80),
        ),
    ]
