# Generated by Django 4.0.1 on 2023-05-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_short_country_short_model_short_season_short_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='length',
            field=models.CharField(default='До линии бедер', max_length=100),
        ),
        migrations.AlterField(
            model_name='short',
            name='size',
            field=models.CharField(default='L (52)', max_length=100),
        ),
    ]
