# Generated by Django 4.0.1 on 2023-05-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0004_alter_size_size_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
