# Generated by Django 4.0.1 on 2023-05-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0005_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shorts.short')),
            ],
        ),
    ]
