# Generated by Django 4.0.1 on 2023-05-30 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0006_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='short',
            name='color',
            field=models.CharField(default='Black', max_length=60),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shorts.short')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
