# Generated by Django 4.0.1 on 2023-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0007_alter_color_color_alter_short_color_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delivery',
            field=models.CharField(default='promptly', max_length=60),
        ),
        migrations.AddField(
            model_name='comment',
            name='material',
            field=models.CharField(default='great', max_length=60),
        ),
        migrations.AddField(
            model_name='comment',
            name='print',
            field=models.CharField(default='great', max_length=60),
        ),
    ]
