# Generated by Django 4.0.1 on 2023-05-31 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0008_comment_delivery_comment_material_comment_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='delivery',
            field=models.CharField(choices=[('early', 'Во время'), ('late', 'Задержали')], default='early', max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='material',
            field=models.CharField(choices=[('great', 'Отличный'), ('good', 'Хороший'), ('bad', 'Плохой')], default='great', max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='print',
            field=models.CharField(choices=[('great', 'Отличный'), ('good', 'Хороший'), ('bad', 'Плохой')], default='great', max_length=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(choices=[('5', 5), ('4', 4), ('3', 3), ('2', 2), ('1', 1)], default=0),
        ),
    ]
