# Generated by Django 4.0.1 on 2023-06-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ'},
        ),
    ]
