# Generated by Django 4.0.1 on 2023-06-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
