# Generated by Django 4.0.1 on 2023-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0014_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
