# Generated by Django 4.0.1 on 2023-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0015_order_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='Black', max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='XXS (40-42)', max_length=25),
        ),
        migrations.AlterField(
            model_name='short',
            name='size',
            field=models.CharField(default='XXS (40-42)', max_length=100),
        ),
    ]
